spring:
  application:
    name: analyzer
  config:
    import: optional:configserver:http://config-server:9091
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 10
server:
  port: 0

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  schema-registry-url: ${KAFKA_SCHEMA_REGISTRY_URL:http://schema-registry:8081}
  user-actions-consumer:
    topic: user-actions
    group-id: user-actions-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  events-similarity-consumer:
    topic: events-similarity
    group-id: events-similarity-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer